spring:
  application:
    name: zsxt
  datasource:
    url: jdbc:mysql://localhost:3306/app
    username: root
    password: '0630'


server:
  port: 8099

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.wang.zsxt.entity






